[colors.bright]
black = "#5a647e"
blue = "#6d9cbe"
cyan = "#519f50"
green = "#a5c261"
magenta = "#b6b3eb"
red = "#da4939"
white = "#f9f7f3"
yellow = "#ffc66d"

[colors.normal]
black = "#2b2b2b"
blue = "#6d9cbe"
cyan = "#519f50"
green = "#a5c261"
magenta = "#b6b3eb"
red = "#da4939"
white = "#e6e1dc"
yellow = "#ffc66d"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Dejavu Sans Mono"
style = "Regular"

[font.offset]
x = -1
